// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: A2R_Control.proto

package sasa5680.DroneProtoMessages;

public final class A2RControl {
  private A2RControl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface A2R_ControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:A2R_Control)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Pitch = 1;</code>
     */
    int getPitch();

    /**
     * <code>int32 Roll = 2;</code>
     */
    int getRoll();

    /**
     * <code>int32 Yaw = 3;</code>
     */
    int getYaw();

    /**
     * <code>int32 Throttle_dir = 4;</code>
     */
    int getThrottleDir();

    /**
     * <code>int32 Throttle_level = 5;</code>
     */
    int getThrottleLevel();
  }
  /**
   * Protobuf type {@code A2R_Control}
   */
  public  static final class A2R_Control extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:A2R_Control)
      A2R_ControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use A2R_Control.newBuilder() to construct.
    private A2R_Control(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private A2R_Control() {
      pitch_ = 0;
      roll_ = 0;
      yaw_ = 0;
      throttleDir_ = 0;
      throttleLevel_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private A2R_Control(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pitch_ = input.readInt32();
              break;
            }
            case 16: {

              roll_ = input.readInt32();
              break;
            }
            case 24: {

              yaw_ = input.readInt32();
              break;
            }
            case 32: {

              throttleDir_ = input.readInt32();
              break;
            }
            case 40: {

              throttleLevel_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sasa5680.DroneProtoMessages.A2RControl.internal_static_A2R_Control_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sasa5680.DroneProtoMessages.A2RControl.internal_static_A2R_Control_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sasa5680.DroneProtoMessages.A2RControl.A2R_Control.class, sasa5680.DroneProtoMessages.A2RControl.A2R_Control.Builder.class);
    }

    public static final int PITCH_FIELD_NUMBER = 1;
    private int pitch_;
    /**
     * <code>int32 Pitch = 1;</code>
     */
    public int getPitch() {
      return pitch_;
    }

    public static final int ROLL_FIELD_NUMBER = 2;
    private int roll_;
    /**
     * <code>int32 Roll = 2;</code>
     */
    public int getRoll() {
      return roll_;
    }

    public static final int YAW_FIELD_NUMBER = 3;
    private int yaw_;
    /**
     * <code>int32 Yaw = 3;</code>
     */
    public int getYaw() {
      return yaw_;
    }

    public static final int THROTTLE_DIR_FIELD_NUMBER = 4;
    private int throttleDir_;
    /**
     * <code>int32 Throttle_dir = 4;</code>
     */
    public int getThrottleDir() {
      return throttleDir_;
    }

    public static final int THROTTLE_LEVEL_FIELD_NUMBER = 5;
    private int throttleLevel_;
    /**
     * <code>int32 Throttle_level = 5;</code>
     */
    public int getThrottleLevel() {
      return throttleLevel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pitch_ != 0) {
        output.writeInt32(1, pitch_);
      }
      if (roll_ != 0) {
        output.writeInt32(2, roll_);
      }
      if (yaw_ != 0) {
        output.writeInt32(3, yaw_);
      }
      if (throttleDir_ != 0) {
        output.writeInt32(4, throttleDir_);
      }
      if (throttleLevel_ != 0) {
        output.writeInt32(5, throttleLevel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pitch_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pitch_);
      }
      if (roll_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roll_);
      }
      if (yaw_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, yaw_);
      }
      if (throttleDir_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, throttleDir_);
      }
      if (throttleLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, throttleLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sasa5680.DroneProtoMessages.A2RControl.A2R_Control)) {
        return super.equals(obj);
      }
      sasa5680.DroneProtoMessages.A2RControl.A2R_Control other = (sasa5680.DroneProtoMessages.A2RControl.A2R_Control) obj;

      boolean result = true;
      result = result && (getPitch()
          == other.getPitch());
      result = result && (getRoll()
          == other.getRoll());
      result = result && (getYaw()
          == other.getYaw());
      result = result && (getThrottleDir()
          == other.getThrottleDir());
      result = result && (getThrottleLevel()
          == other.getThrottleLevel());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PITCH_FIELD_NUMBER;
      hash = (53 * hash) + getPitch();
      hash = (37 * hash) + ROLL_FIELD_NUMBER;
      hash = (53 * hash) + getRoll();
      hash = (37 * hash) + YAW_FIELD_NUMBER;
      hash = (53 * hash) + getYaw();
      hash = (37 * hash) + THROTTLE_DIR_FIELD_NUMBER;
      hash = (53 * hash) + getThrottleDir();
      hash = (37 * hash) + THROTTLE_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getThrottleLevel();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sasa5680.DroneProtoMessages.A2RControl.A2R_Control prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code A2R_Control}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:A2R_Control)
        sasa5680.DroneProtoMessages.A2RControl.A2R_ControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sasa5680.DroneProtoMessages.A2RControl.internal_static_A2R_Control_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sasa5680.DroneProtoMessages.A2RControl.internal_static_A2R_Control_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sasa5680.DroneProtoMessages.A2RControl.A2R_Control.class, sasa5680.DroneProtoMessages.A2RControl.A2R_Control.Builder.class);
      }

      // Construct using sasa5680.DroneProtoMessages.A2RControl.A2R_Control.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pitch_ = 0;

        roll_ = 0;

        yaw_ = 0;

        throttleDir_ = 0;

        throttleLevel_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sasa5680.DroneProtoMessages.A2RControl.internal_static_A2R_Control_descriptor;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.A2RControl.A2R_Control getDefaultInstanceForType() {
        return sasa5680.DroneProtoMessages.A2RControl.A2R_Control.getDefaultInstance();
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.A2RControl.A2R_Control build() {
        sasa5680.DroneProtoMessages.A2RControl.A2R_Control result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.A2RControl.A2R_Control buildPartial() {
        sasa5680.DroneProtoMessages.A2RControl.A2R_Control result = new sasa5680.DroneProtoMessages.A2RControl.A2R_Control(this);
        result.pitch_ = pitch_;
        result.roll_ = roll_;
        result.yaw_ = yaw_;
        result.throttleDir_ = throttleDir_;
        result.throttleLevel_ = throttleLevel_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sasa5680.DroneProtoMessages.A2RControl.A2R_Control) {
          return mergeFrom((sasa5680.DroneProtoMessages.A2RControl.A2R_Control)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sasa5680.DroneProtoMessages.A2RControl.A2R_Control other) {
        if (other == sasa5680.DroneProtoMessages.A2RControl.A2R_Control.getDefaultInstance()) return this;
        if (other.getPitch() != 0) {
          setPitch(other.getPitch());
        }
        if (other.getRoll() != 0) {
          setRoll(other.getRoll());
        }
        if (other.getYaw() != 0) {
          setYaw(other.getYaw());
        }
        if (other.getThrottleDir() != 0) {
          setThrottleDir(other.getThrottleDir());
        }
        if (other.getThrottleLevel() != 0) {
          setThrottleLevel(other.getThrottleLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sasa5680.DroneProtoMessages.A2RControl.A2R_Control parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sasa5680.DroneProtoMessages.A2RControl.A2R_Control) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pitch_ ;
      /**
       * <code>int32 Pitch = 1;</code>
       */
      public int getPitch() {
        return pitch_;
      }
      /**
       * <code>int32 Pitch = 1;</code>
       */
      public Builder setPitch(int value) {
        
        pitch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Pitch = 1;</code>
       */
      public Builder clearPitch() {
        
        pitch_ = 0;
        onChanged();
        return this;
      }

      private int roll_ ;
      /**
       * <code>int32 Roll = 2;</code>
       */
      public int getRoll() {
        return roll_;
      }
      /**
       * <code>int32 Roll = 2;</code>
       */
      public Builder setRoll(int value) {
        
        roll_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Roll = 2;</code>
       */
      public Builder clearRoll() {
        
        roll_ = 0;
        onChanged();
        return this;
      }

      private int yaw_ ;
      /**
       * <code>int32 Yaw = 3;</code>
       */
      public int getYaw() {
        return yaw_;
      }
      /**
       * <code>int32 Yaw = 3;</code>
       */
      public Builder setYaw(int value) {
        
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Yaw = 3;</code>
       */
      public Builder clearYaw() {
        
        yaw_ = 0;
        onChanged();
        return this;
      }

      private int throttleDir_ ;
      /**
       * <code>int32 Throttle_dir = 4;</code>
       */
      public int getThrottleDir() {
        return throttleDir_;
      }
      /**
       * <code>int32 Throttle_dir = 4;</code>
       */
      public Builder setThrottleDir(int value) {
        
        throttleDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Throttle_dir = 4;</code>
       */
      public Builder clearThrottleDir() {
        
        throttleDir_ = 0;
        onChanged();
        return this;
      }

      private int throttleLevel_ ;
      /**
       * <code>int32 Throttle_level = 5;</code>
       */
      public int getThrottleLevel() {
        return throttleLevel_;
      }
      /**
       * <code>int32 Throttle_level = 5;</code>
       */
      public Builder setThrottleLevel(int value) {
        
        throttleLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Throttle_level = 5;</code>
       */
      public Builder clearThrottleLevel() {
        
        throttleLevel_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:A2R_Control)
    }

    // @@protoc_insertion_point(class_scope:A2R_Control)
    private static final sasa5680.DroneProtoMessages.A2RControl.A2R_Control DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sasa5680.DroneProtoMessages.A2RControl.A2R_Control();
    }

    public static sasa5680.DroneProtoMessages.A2RControl.A2R_Control getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<A2R_Control>
        PARSER = new com.google.protobuf.AbstractParser<A2R_Control>() {
      @java.lang.Override
      public A2R_Control parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new A2R_Control(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<A2R_Control> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<A2R_Control> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sasa5680.DroneProtoMessages.A2RControl.A2R_Control getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_A2R_Control_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_A2R_Control_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021A2R_Control.proto\"e\n\013A2R_Control\022\r\n\005Pi" +
      "tch\030\001 \001(\005\022\014\n\004Roll\030\002 \001(\005\022\013\n\003Yaw\030\003 \001(\005\022\024\n\014" +
      "Throttle_dir\030\004 \001(\005\022\026\n\016Throttle_level\030\005 \001" +
      "(\005B\035\n\033sasa5680.DroneProtoMessagesb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_A2R_Control_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_A2R_Control_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_A2R_Control_descriptor,
        new java.lang.String[] { "Pitch", "Roll", "Yaw", "ThrottleDir", "ThrottleLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
