// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2S_ConnectionFlag.proto

package sasa5680.DroneProtoMessages;

public final class C2SConnectionFlag {
  private C2SConnectionFlag() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_ConnectionFlagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2S_ConnectionFlag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool Con = 1;</code>
     */
    boolean getCon();
  }
  /**
   * Protobuf type {@code C2S_ConnectionFlag}
   */
  public  static final class C2S_ConnectionFlag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C2S_ConnectionFlag)
      C2S_ConnectionFlagOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_ConnectionFlag.newBuilder() to construct.
    private C2S_ConnectionFlag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_ConnectionFlag() {
      con_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_ConnectionFlag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              con_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sasa5680.DroneProtoMessages.C2SConnectionFlag.internal_static_C2S_ConnectionFlag_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sasa5680.DroneProtoMessages.C2SConnectionFlag.internal_static_C2S_ConnectionFlag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag.class, sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag.Builder.class);
    }

    public static final int CON_FIELD_NUMBER = 1;
    private boolean con_;
    /**
     * <code>bool Con = 1;</code>
     */
    public boolean getCon() {
      return con_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (con_ != false) {
        output.writeBool(1, con_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (con_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, con_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag)) {
        return super.equals(obj);
      }
      sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag other = (sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag) obj;

      boolean result = true;
      result = result && (getCon()
          == other.getCon());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCon());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_ConnectionFlag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2S_ConnectionFlag)
        sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sasa5680.DroneProtoMessages.C2SConnectionFlag.internal_static_C2S_ConnectionFlag_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sasa5680.DroneProtoMessages.C2SConnectionFlag.internal_static_C2S_ConnectionFlag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag.class, sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag.Builder.class);
      }

      // Construct using sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        con_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sasa5680.DroneProtoMessages.C2SConnectionFlag.internal_static_C2S_ConnectionFlag_descriptor;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag getDefaultInstanceForType() {
        return sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag.getDefaultInstance();
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag build() {
        sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag buildPartial() {
        sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag result = new sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag(this);
        result.con_ = con_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag) {
          return mergeFrom((sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag other) {
        if (other == sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag.getDefaultInstance()) return this;
        if (other.getCon() != false) {
          setCon(other.getCon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean con_ ;
      /**
       * <code>bool Con = 1;</code>
       */
      public boolean getCon() {
        return con_;
      }
      /**
       * <code>bool Con = 1;</code>
       */
      public Builder setCon(boolean value) {
        
        con_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Con = 1;</code>
       */
      public Builder clearCon() {
        
        con_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C2S_ConnectionFlag)
    }

    // @@protoc_insertion_point(class_scope:C2S_ConnectionFlag)
    private static final sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag();
    }

    public static sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2S_ConnectionFlag>
        PARSER = new com.google.protobuf.AbstractParser<C2S_ConnectionFlag>() {
      @java.lang.Override
      public C2S_ConnectionFlag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_ConnectionFlag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_ConnectionFlag> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_ConnectionFlag> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sasa5680.DroneProtoMessages.C2SConnectionFlag.C2S_ConnectionFlag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_ConnectionFlag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C2S_ConnectionFlag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030C2S_ConnectionFlag.proto\"!\n\022C2S_Connec" +
      "tionFlag\022\013\n\003Con\030\001 \001(\010B\035\n\033sasa5680.DroneP" +
      "rotoMessagesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_C2S_ConnectionFlag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C2S_ConnectionFlag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C2S_ConnectionFlag_descriptor,
        new java.lang.String[] { "Con", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
