// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: General.proto

package sasa5680.DroneProtoMessages;

public final class GeneralOuterClass {
  private GeneralOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GeneralOrBuilder extends
      // @@protoc_insertion_point(interface_extends:General)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string MessageType = 1;</code>
     */
    java.lang.String getMessageType();
    /**
     * <code>string MessageType = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes();

    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getInnerMSGList();
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    com.google.protobuf.Any getInnerMSG(int index);
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    int getInnerMSGCount();
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getInnerMSGOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getInnerMSGOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code General}
   */
  public  static final class General extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:General)
      GeneralOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use General.newBuilder() to construct.
    private General(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private General() {
      messageType_ = "";
      innerMSG_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private General(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageType_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                innerMSG_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000002;
              }
              innerMSG_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          innerMSG_ = java.util.Collections.unmodifiableList(innerMSG_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sasa5680.DroneProtoMessages.GeneralOuterClass.internal_static_General_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sasa5680.DroneProtoMessages.GeneralOuterClass.internal_static_General_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sasa5680.DroneProtoMessages.GeneralOuterClass.General.class, sasa5680.DroneProtoMessages.GeneralOuterClass.General.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageType_;
    /**
     * <code>string MessageType = 1;</code>
     */
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      }
    }
    /**
     * <code>string MessageType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INNERMSG_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.Any> innerMSG_;
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    public java.util.List<com.google.protobuf.Any> getInnerMSGList() {
      return innerMSG_;
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getInnerMSGOrBuilderList() {
      return innerMSG_;
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    public int getInnerMSGCount() {
      return innerMSG_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    public com.google.protobuf.Any getInnerMSG(int index) {
      return innerMSG_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getInnerMSGOrBuilder(
        int index) {
      return innerMSG_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageType_);
      }
      for (int i = 0; i < innerMSG_.size(); i++) {
        output.writeMessage(2, innerMSG_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageType_);
      }
      for (int i = 0; i < innerMSG_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, innerMSG_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sasa5680.DroneProtoMessages.GeneralOuterClass.General)) {
        return super.equals(obj);
      }
      sasa5680.DroneProtoMessages.GeneralOuterClass.General other = (sasa5680.DroneProtoMessages.GeneralOuterClass.General) obj;

      boolean result = true;
      result = result && getMessageType()
          .equals(other.getMessageType());
      result = result && getInnerMSGList()
          .equals(other.getInnerMSGList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
      if (getInnerMSGCount() > 0) {
        hash = (37 * hash) + INNERMSG_FIELD_NUMBER;
        hash = (53 * hash) + getInnerMSGList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sasa5680.DroneProtoMessages.GeneralOuterClass.General prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code General}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:General)
        sasa5680.DroneProtoMessages.GeneralOuterClass.GeneralOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sasa5680.DroneProtoMessages.GeneralOuterClass.internal_static_General_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sasa5680.DroneProtoMessages.GeneralOuterClass.internal_static_General_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sasa5680.DroneProtoMessages.GeneralOuterClass.General.class, sasa5680.DroneProtoMessages.GeneralOuterClass.General.Builder.class);
      }

      // Construct using sasa5680.DroneProtoMessages.GeneralOuterClass.General.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInnerMSGFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = "";

        if (innerMSGBuilder_ == null) {
          innerMSG_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          innerMSGBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sasa5680.DroneProtoMessages.GeneralOuterClass.internal_static_General_descriptor;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.GeneralOuterClass.General getDefaultInstanceForType() {
        return sasa5680.DroneProtoMessages.GeneralOuterClass.General.getDefaultInstance();
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.GeneralOuterClass.General build() {
        sasa5680.DroneProtoMessages.GeneralOuterClass.General result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.GeneralOuterClass.General buildPartial() {
        sasa5680.DroneProtoMessages.GeneralOuterClass.General result = new sasa5680.DroneProtoMessages.GeneralOuterClass.General(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.messageType_ = messageType_;
        if (innerMSGBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            innerMSG_ = java.util.Collections.unmodifiableList(innerMSG_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.innerMSG_ = innerMSG_;
        } else {
          result.innerMSG_ = innerMSGBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sasa5680.DroneProtoMessages.GeneralOuterClass.General) {
          return mergeFrom((sasa5680.DroneProtoMessages.GeneralOuterClass.General)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sasa5680.DroneProtoMessages.GeneralOuterClass.General other) {
        if (other == sasa5680.DroneProtoMessages.GeneralOuterClass.General.getDefaultInstance()) return this;
        if (!other.getMessageType().isEmpty()) {
          messageType_ = other.messageType_;
          onChanged();
        }
        if (innerMSGBuilder_ == null) {
          if (!other.innerMSG_.isEmpty()) {
            if (innerMSG_.isEmpty()) {
              innerMSG_ = other.innerMSG_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInnerMSGIsMutable();
              innerMSG_.addAll(other.innerMSG_);
            }
            onChanged();
          }
        } else {
          if (!other.innerMSG_.isEmpty()) {
            if (innerMSGBuilder_.isEmpty()) {
              innerMSGBuilder_.dispose();
              innerMSGBuilder_ = null;
              innerMSG_ = other.innerMSG_;
              bitField0_ = (bitField0_ & ~0x00000002);
              innerMSGBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInnerMSGFieldBuilder() : null;
            } else {
              innerMSGBuilder_.addAllMessages(other.innerMSG_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sasa5680.DroneProtoMessages.GeneralOuterClass.General parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sasa5680.DroneProtoMessages.GeneralOuterClass.General) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageType_ = "";
      /**
       * <code>string MessageType = 1;</code>
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string MessageType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MessageType = 1;</code>
       */
      public Builder setMessageType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MessageType = 1;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = getDefaultInstance().getMessageType();
        onChanged();
        return this;
      }
      /**
       * <code>string MessageType = 1;</code>
       */
      public Builder setMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> innerMSG_ =
        java.util.Collections.emptyList();
      private void ensureInnerMSGIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          innerMSG_ = new java.util.ArrayList<com.google.protobuf.Any>(innerMSG_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> innerMSGBuilder_;

      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public java.util.List<com.google.protobuf.Any> getInnerMSGList() {
        if (innerMSGBuilder_ == null) {
          return java.util.Collections.unmodifiableList(innerMSG_);
        } else {
          return innerMSGBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public int getInnerMSGCount() {
        if (innerMSGBuilder_ == null) {
          return innerMSG_.size();
        } else {
          return innerMSGBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public com.google.protobuf.Any getInnerMSG(int index) {
        if (innerMSGBuilder_ == null) {
          return innerMSG_.get(index);
        } else {
          return innerMSGBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder setInnerMSG(
          int index, com.google.protobuf.Any value) {
        if (innerMSGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerMSGIsMutable();
          innerMSG_.set(index, value);
          onChanged();
        } else {
          innerMSGBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder setInnerMSG(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.set(index, builderForValue.build());
          onChanged();
        } else {
          innerMSGBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder addInnerMSG(com.google.protobuf.Any value) {
        if (innerMSGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerMSGIsMutable();
          innerMSG_.add(value);
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder addInnerMSG(
          int index, com.google.protobuf.Any value) {
        if (innerMSGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerMSGIsMutable();
          innerMSG_.add(index, value);
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder addInnerMSG(
          com.google.protobuf.Any.Builder builderForValue) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.add(builderForValue.build());
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder addInnerMSG(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.add(index, builderForValue.build());
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder addAllInnerMSG(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, innerMSG_);
          onChanged();
        } else {
          innerMSGBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder clearInnerMSG() {
        if (innerMSGBuilder_ == null) {
          innerMSG_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          innerMSGBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public Builder removeInnerMSG(int index) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.remove(index);
          onChanged();
        } else {
          innerMSGBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public com.google.protobuf.Any.Builder getInnerMSGBuilder(
          int index) {
        return getInnerMSGFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getInnerMSGOrBuilder(
          int index) {
        if (innerMSGBuilder_ == null) {
          return innerMSG_.get(index);  } else {
          return innerMSGBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getInnerMSGOrBuilderList() {
        if (innerMSGBuilder_ != null) {
          return innerMSGBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(innerMSG_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public com.google.protobuf.Any.Builder addInnerMSGBuilder() {
        return getInnerMSGFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public com.google.protobuf.Any.Builder addInnerMSGBuilder(
          int index) {
        return getInnerMSGFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 2;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getInnerMSGBuilderList() {
        return getInnerMSGFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getInnerMSGFieldBuilder() {
        if (innerMSGBuilder_ == null) {
          innerMSGBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  innerMSG_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          innerMSG_ = null;
        }
        return innerMSGBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:General)
    }

    // @@protoc_insertion_point(class_scope:General)
    private static final sasa5680.DroneProtoMessages.GeneralOuterClass.General DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sasa5680.DroneProtoMessages.GeneralOuterClass.General();
    }

    public static sasa5680.DroneProtoMessages.GeneralOuterClass.General getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<General>
        PARSER = new com.google.protobuf.AbstractParser<General>() {
      @java.lang.Override
      public General parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new General(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<General> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<General> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sasa5680.DroneProtoMessages.GeneralOuterClass.General getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_General_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_General_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGeneral.proto\032\031google/protobuf/any.pro" +
      "to\"F\n\007General\022\023\n\013MessageType\030\001 \001(\t\022&\n\010in" +
      "nerMSG\030\002 \003(\0132\024.google.protobuf.AnyB\035\n\033sa" +
      "sa5680.DroneProtoMessagesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_General_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_General_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_General_descriptor,
        new java.lang.String[] { "MessageType", "InnerMSG", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
