// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: R2A_DeviceData.proto

package sasa5680.DroneProtoMessages;

public final class R2ADeviceData {
  private R2ADeviceData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface R2A_DeviceDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:R2A_DeviceData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string GPS_Latitude = 1;</code>
     */
    java.lang.String getGPSLatitude();
    /**
     * <code>string GPS_Latitude = 1;</code>
     */
    com.google.protobuf.ByteString
        getGPSLatitudeBytes();

    /**
     * <code>string GPS_Longitude = 2;</code>
     */
    java.lang.String getGPSLongitude();
    /**
     * <code>string GPS_Longitude = 2;</code>
     */
    com.google.protobuf.ByteString
        getGPSLongitudeBytes();

    /**
     * <code>float altitude = 3;</code>
     */
    float getAltitude();

    /**
     * <code>float battery = 4;</code>
     */
    float getBattery();

    /**
     * <code>string state = 5;</code>
     */
    java.lang.String getState();
    /**
     * <code>string state = 5;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();
  }
  /**
   * Protobuf type {@code R2A_DeviceData}
   */
  public  static final class R2A_DeviceData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:R2A_DeviceData)
      R2A_DeviceDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use R2A_DeviceData.newBuilder() to construct.
    private R2A_DeviceData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private R2A_DeviceData() {
      gPSLatitude_ = "";
      gPSLongitude_ = "";
      altitude_ = 0F;
      battery_ = 0F;
      state_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private R2A_DeviceData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              gPSLatitude_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              gPSLongitude_ = s;
              break;
            }
            case 29: {

              altitude_ = input.readFloat();
              break;
            }
            case 37: {

              battery_ = input.readFloat();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sasa5680.DroneProtoMessages.R2ADeviceData.internal_static_R2A_DeviceData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sasa5680.DroneProtoMessages.R2ADeviceData.internal_static_R2A_DeviceData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData.class, sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData.Builder.class);
    }

    public static final int GPS_LATITUDE_FIELD_NUMBER = 1;
    private volatile java.lang.Object gPSLatitude_;
    /**
     * <code>string GPS_Latitude = 1;</code>
     */
    public java.lang.String getGPSLatitude() {
      java.lang.Object ref = gPSLatitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gPSLatitude_ = s;
        return s;
      }
    }
    /**
     * <code>string GPS_Latitude = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGPSLatitudeBytes() {
      java.lang.Object ref = gPSLatitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gPSLatitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GPS_LONGITUDE_FIELD_NUMBER = 2;
    private volatile java.lang.Object gPSLongitude_;
    /**
     * <code>string GPS_Longitude = 2;</code>
     */
    public java.lang.String getGPSLongitude() {
      java.lang.Object ref = gPSLongitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gPSLongitude_ = s;
        return s;
      }
    }
    /**
     * <code>string GPS_Longitude = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGPSLongitudeBytes() {
      java.lang.Object ref = gPSLongitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gPSLongitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALTITUDE_FIELD_NUMBER = 3;
    private float altitude_;
    /**
     * <code>float altitude = 3;</code>
     */
    public float getAltitude() {
      return altitude_;
    }

    public static final int BATTERY_FIELD_NUMBER = 4;
    private float battery_;
    /**
     * <code>float battery = 4;</code>
     */
    public float getBattery() {
      return battery_;
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object state_;
    /**
     * <code>string state = 5;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string state = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGPSLatitudeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, gPSLatitude_);
      }
      if (!getGPSLongitudeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gPSLongitude_);
      }
      if (altitude_ != 0F) {
        output.writeFloat(3, altitude_);
      }
      if (battery_ != 0F) {
        output.writeFloat(4, battery_);
      }
      if (!getStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGPSLatitudeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, gPSLatitude_);
      }
      if (!getGPSLongitudeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gPSLongitude_);
      }
      if (altitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, altitude_);
      }
      if (battery_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, battery_);
      }
      if (!getStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData)) {
        return super.equals(obj);
      }
      sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData other = (sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData) obj;

      boolean result = true;
      result = result && getGPSLatitude()
          .equals(other.getGPSLatitude());
      result = result && getGPSLongitude()
          .equals(other.getGPSLongitude());
      result = result && (
          java.lang.Float.floatToIntBits(getAltitude())
          == java.lang.Float.floatToIntBits(
              other.getAltitude()));
      result = result && (
          java.lang.Float.floatToIntBits(getBattery())
          == java.lang.Float.floatToIntBits(
              other.getBattery()));
      result = result && getState()
          .equals(other.getState());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GPS_LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getGPSLatitude().hashCode();
      hash = (37 * hash) + GPS_LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getGPSLongitude().hashCode();
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAltitude());
      hash = (37 * hash) + BATTERY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBattery());
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code R2A_DeviceData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:R2A_DeviceData)
        sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sasa5680.DroneProtoMessages.R2ADeviceData.internal_static_R2A_DeviceData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sasa5680.DroneProtoMessages.R2ADeviceData.internal_static_R2A_DeviceData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData.class, sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData.Builder.class);
      }

      // Construct using sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        gPSLatitude_ = "";

        gPSLongitude_ = "";

        altitude_ = 0F;

        battery_ = 0F;

        state_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sasa5680.DroneProtoMessages.R2ADeviceData.internal_static_R2A_DeviceData_descriptor;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData getDefaultInstanceForType() {
        return sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData.getDefaultInstance();
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData build() {
        sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData buildPartial() {
        sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData result = new sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData(this);
        result.gPSLatitude_ = gPSLatitude_;
        result.gPSLongitude_ = gPSLongitude_;
        result.altitude_ = altitude_;
        result.battery_ = battery_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData) {
          return mergeFrom((sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData other) {
        if (other == sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData.getDefaultInstance()) return this;
        if (!other.getGPSLatitude().isEmpty()) {
          gPSLatitude_ = other.gPSLatitude_;
          onChanged();
        }
        if (!other.getGPSLongitude().isEmpty()) {
          gPSLongitude_ = other.gPSLongitude_;
          onChanged();
        }
        if (other.getAltitude() != 0F) {
          setAltitude(other.getAltitude());
        }
        if (other.getBattery() != 0F) {
          setBattery(other.getBattery());
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object gPSLatitude_ = "";
      /**
       * <code>string GPS_Latitude = 1;</code>
       */
      public java.lang.String getGPSLatitude() {
        java.lang.Object ref = gPSLatitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gPSLatitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string GPS_Latitude = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGPSLatitudeBytes() {
        java.lang.Object ref = gPSLatitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gPSLatitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string GPS_Latitude = 1;</code>
       */
      public Builder setGPSLatitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gPSLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string GPS_Latitude = 1;</code>
       */
      public Builder clearGPSLatitude() {
        
        gPSLatitude_ = getDefaultInstance().getGPSLatitude();
        onChanged();
        return this;
      }
      /**
       * <code>string GPS_Latitude = 1;</code>
       */
      public Builder setGPSLatitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gPSLatitude_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gPSLongitude_ = "";
      /**
       * <code>string GPS_Longitude = 2;</code>
       */
      public java.lang.String getGPSLongitude() {
        java.lang.Object ref = gPSLongitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gPSLongitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string GPS_Longitude = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGPSLongitudeBytes() {
        java.lang.Object ref = gPSLongitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gPSLongitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string GPS_Longitude = 2;</code>
       */
      public Builder setGPSLongitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gPSLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string GPS_Longitude = 2;</code>
       */
      public Builder clearGPSLongitude() {
        
        gPSLongitude_ = getDefaultInstance().getGPSLongitude();
        onChanged();
        return this;
      }
      /**
       * <code>string GPS_Longitude = 2;</code>
       */
      public Builder setGPSLongitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gPSLongitude_ = value;
        onChanged();
        return this;
      }

      private float altitude_ ;
      /**
       * <code>float altitude = 3;</code>
       */
      public float getAltitude() {
        return altitude_;
      }
      /**
       * <code>float altitude = 3;</code>
       */
      public Builder setAltitude(float value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float altitude = 3;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0F;
        onChanged();
        return this;
      }

      private float battery_ ;
      /**
       * <code>float battery = 4;</code>
       */
      public float getBattery() {
        return battery_;
      }
      /**
       * <code>float battery = 4;</code>
       */
      public Builder setBattery(float value) {
        
        battery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float battery = 4;</code>
       */
      public Builder clearBattery() {
        
        battery_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string state = 5;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string state = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string state = 5;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string state = 5;</code>
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>string state = 5;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:R2A_DeviceData)
    }

    // @@protoc_insertion_point(class_scope:R2A_DeviceData)
    private static final sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData();
    }

    public static sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<R2A_DeviceData>
        PARSER = new com.google.protobuf.AbstractParser<R2A_DeviceData>() {
      @java.lang.Override
      public R2A_DeviceData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new R2A_DeviceData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<R2A_DeviceData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<R2A_DeviceData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sasa5680.DroneProtoMessages.R2ADeviceData.R2A_DeviceData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_R2A_DeviceData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_R2A_DeviceData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024R2A_DeviceData.proto\"o\n\016R2A_DeviceData" +
      "\022\024\n\014GPS_Latitude\030\001 \001(\t\022\025\n\rGPS_Longitude\030" +
      "\002 \001(\t\022\020\n\010altitude\030\003 \001(\002\022\017\n\007battery\030\004 \001(\002" +
      "\022\r\n\005state\030\005 \001(\tB\035\n\033sasa5680.DroneProtoMe" +
      "ssagesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_R2A_DeviceData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_R2A_DeviceData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_R2A_DeviceData_descriptor,
        new java.lang.String[] { "GPSLatitude", "GPSLongitude", "Altitude", "Battery", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
