// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2C_ClientIP.proto

package sasa5680.DroneProtoMessages;

public final class S2CClientIP {
  private S2CClientIP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2C_ClientIPOrBuilder extends
      // @@protoc_insertion_point(interface_extends:S2C_ClientIP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string IP = 1;</code>
     */
    java.lang.String getIP();
    /**
     * <code>string IP = 1;</code>
     */
    com.google.protobuf.ByteString
        getIPBytes();
  }
  /**
   * Protobuf type {@code S2C_ClientIP}
   */
  public  static final class S2C_ClientIP extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:S2C_ClientIP)
      S2C_ClientIPOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_ClientIP.newBuilder() to construct.
    private S2C_ClientIP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_ClientIP() {
      iP_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_ClientIP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              iP_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sasa5680.DroneProtoMessages.S2CClientIP.internal_static_S2C_ClientIP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sasa5680.DroneProtoMessages.S2CClientIP.internal_static_S2C_ClientIP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP.class, sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile java.lang.Object iP_;
    /**
     * <code>string IP = 1;</code>
     */
    public java.lang.String getIP() {
      java.lang.Object ref = iP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iP_ = s;
        return s;
      }
    }
    /**
     * <code>string IP = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIPBytes() {
      java.lang.Object ref = iP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIPBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, iP_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIPBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, iP_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP)) {
        return super.equals(obj);
      }
      sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP other = (sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP) obj;

      boolean result = true;
      result = result && getIP()
          .equals(other.getIP());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIP().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code S2C_ClientIP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:S2C_ClientIP)
        sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sasa5680.DroneProtoMessages.S2CClientIP.internal_static_S2C_ClientIP_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sasa5680.DroneProtoMessages.S2CClientIP.internal_static_S2C_ClientIP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP.class, sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP.Builder.class);
      }

      // Construct using sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        iP_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sasa5680.DroneProtoMessages.S2CClientIP.internal_static_S2C_ClientIP_descriptor;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP getDefaultInstanceForType() {
        return sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP.getDefaultInstance();
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP build() {
        sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP buildPartial() {
        sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP result = new sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP(this);
        result.iP_ = iP_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP) {
          return mergeFrom((sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP other) {
        if (other == sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP.getDefaultInstance()) return this;
        if (!other.getIP().isEmpty()) {
          iP_ = other.iP_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object iP_ = "";
      /**
       * <code>string IP = 1;</code>
       */
      public java.lang.String getIP() {
        java.lang.Object ref = iP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string IP = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIPBytes() {
        java.lang.Object ref = iP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string IP = 1;</code>
       */
      public Builder setIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string IP = 1;</code>
       */
      public Builder clearIP() {
        
        iP_ = getDefaultInstance().getIP();
        onChanged();
        return this;
      }
      /**
       * <code>string IP = 1;</code>
       */
      public Builder setIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iP_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:S2C_ClientIP)
    }

    // @@protoc_insertion_point(class_scope:S2C_ClientIP)
    private static final sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP();
    }

    public static sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2C_ClientIP>
        PARSER = new com.google.protobuf.AbstractParser<S2C_ClientIP>() {
      @java.lang.Override
      public S2C_ClientIP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_ClientIP(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_ClientIP> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_ClientIP> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sasa5680.DroneProtoMessages.S2CClientIP.S2C_ClientIP getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_S2C_ClientIP_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_S2C_ClientIP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022S2C_ClientIP.proto\"\032\n\014S2C_ClientIP\022\n\n\002" +
      "IP\030\001 \001(\tB\035\n\033sasa5680.DroneProtoMessagesb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_S2C_ClientIP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_S2C_ClientIP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_S2C_ClientIP_descriptor,
        new java.lang.String[] { "IP", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
